apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-manager
  namespace: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-manager
        name: redis-manager
    spec:
      containers:
        - name: redis-manager
          image: dungez/redis-manager
          args:
           - /bin/bash